#!/usr/bin/python3
from os import listdir, system
from sys import path as spath


def errexit():
    print("Compilation error, exiting")
    exit(1)


spath.append("./submodules/CircuitMPY/")
import circuitmpy

circuitmpy.fetch_mpy()


def load_manifest() -> str:
    print("[1/4] Loading manifest")
    with open("package_files.txt") as f:
        raw_data = f.readlines()
        tab_data = []
        for i in raw_data:
            tab_data.append(i[:-1].split(" "))
        return tab_data


def mk_scripts(data: list) -> None:
    print("[2/4] Generating scripts and binaries")
    autogen_msg = "# This is an automatically generated script, please do not edit this file manually.\n\n"
    inst = autogen_msg
    strap = autogen_msg
    uninst = autogen_msg

    files = []
    targets = []
    rmfol = []

    sent_rml = False

    for i in data:
        print("[-/-] " + i[0].upper() + " " + i[-1])
        if i[0] == "folder":
            inst += 'be.based.run("mkdir ' + i[1] + '")\n'
            strap += (
                'try:\n    mkdir(path.join(root, "'
                + i[1][1:]
                + '"))\nexcept FileExistsError:\n    pass\n'
            )
            rmfol.append(i[1])
        elif i[0] == "file":
            inst += 'be.based.run("cp ' + i[1] + " " + i[2] + '")\n'
            strap += (
                'shutil.copyfile("' + i[1] + '", path.join(root, "' + i[2][1:] + '"))\n'
            )
            if not sent_rml:
                sent_rml = True
                uninst += 'be.based.run("rm'
            uninst += " " + i[2]
        elif i[0] == "mpy":
            try:
                circuitmpy.compile_mpy(i[1], "files/" + i[2])
            except:
                errexit()
        else:
            raise RuntimeError("Unknown command " + str(i[0]) + "!")

    if sent_rml:
        uninst += '")\n'
    rmfol.reverse()
    for i in rmfol:
        uninst += 'be.based.run("rmdir ' + i + '")\n'

    signoff = 'be.api.setvar("return", "0")\n'
    inst += signoff
    uninst += signoff

    with open("files/installer.py", "w") as f:
        f.write(inst)
    with open("files/strap.py", "w") as f:
        f.write(strap)
    with open("files/uninstaller.py", "w") as f:
        f.write(uninst)


if __name__ == "__main__":
    manifest = load_manifest()
    mk_scripts(manifest)
